# Generated by Django 3.0.7 on 2020-07-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('caddr', models.CharField(max_length=200)),
                ('cmob_no', models.IntegerField()),
            ],
        ),
    ]
